/*
 *
 *    You may use and distribute under the terms of either the GNU Lesser
 *    General Public License, either version 2 of the license or,
 *    at your choice, any later version. Alternatively, you may use and
 *    distribute under the terms of the XPL.
 *
 *    See the LICENSE.lgpl and LICENSE.xpl files for the specific terms of
 *    the licenses.
 *
 *    This software is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the README
 *    file for more details.
 *
 */
/*
 *    Generated by GZigZag - DO NOT MODIFY!
 *    If you find something wrong that should be fixed,
 *    PLEASE FIX THE CODE THAT GENERATES THIS CLASS!
 */

package org.gzigzag.modules.mm;

public class MediaZOb {
    public final org.gzigzag.Stepper x;
    public final org.gzigzag.Stepper y;

    public MediaZOb(org.gzigzag.Stepper s) {
	    x = (org.gzigzag.Stepper)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC479602E300048C67285A5B7AD5240E65EB2E1B867BB1BDABFA6827D8D99F-5"));
	    y = (org.gzigzag.Stepper)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC479602E300048C67285A5B7AD5240E65EB2E1B867BB1BDABFA6827D8D99F-6"));
    }


}
