/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gzigzag_module_SimplePlayer */

#ifndef _Included_org_gzigzag_module_SimplePlayer
#define _Included_org_gzigzag_module_SimplePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gzigzag_module_SimplePlayer
 * Method:    player_init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gzigzag_module_SimplePlayer_player_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_gzigzag_module_SimplePlayer
 * Method:    player_start
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_org_gzigzag_module_SimplePlayer_player_1start
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     org_gzigzag_module_SimplePlayer
 * Method:    player_getCurrentOffset
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_gzigzag_module_SimplePlayer_player_1getCurrentOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gzigzag_module_SimplePlayer
 * Method:    player_stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gzigzag_module_SimplePlayer_player_1stop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
