/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gzigzag_module_SimpleRecorder */

#ifndef _Included_org_gzigzag_module_SimpleRecorder
#define _Included_org_gzigzag_module_SimpleRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gzigzag_module_SimpleRecorder
 * Method:    recorder_start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gzigzag_module_SimpleRecorder_recorder_1start
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gzigzag_module_SimpleRecorder
 * Method:    recorder_stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gzigzag_module_SimpleRecorder_recorder_1stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gzigzag_module_SimpleRecorder
 * Method:    recorder_init
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_gzigzag_module_SimpleRecorder_recorder_1init
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     org_gzigzag_module_SimpleRecorder
 * Method:    recorder_getCurrentOffset
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_gzigzag_module_SimpleRecorder_recorder_1getCurrentOffset
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
