DIAGRAMS=../../wmlinc/article.wml \
	rank1vert.png rank2vert.png rank3both.png permascroll.png

all: ct.html ct-ns4.html

ct.html: ct.wml $(DIAGRAMS)

ct-ns4.html: ct.wml $(DIAGRAMS)

include ../../lib.mk

