/*
 *
 *    You may use and distribute under the terms of either the GNU Lesser
 *    General Public License, either version 2 of the license or,
 *    at your choice, any later version. Alternatively, you may use and
 *    distribute under the terms of the XPL.
 *
 *    See the LICENSE.lgpl and LICENSE.xpl files for the specific terms of
 *    the licenses.
 *
 *    This software is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the README
 *    file for more details.
 *
 */
/*
 *    Generated by GZigZag - DO NOT MODIFY!
 *    If you find something wrong that should be fixed,
 *    PLEASE FIX THE CODE THAT GENERATES THIS CLASS!
 */

package org.gzigzag.impl;

public class JavaZOb {
    public final org.gzigzag.Stepper members;
    public final java.lang.String packageName;
    public final java.lang.String path;
    public final org.gzigzag.Stepper code;
    public final java.lang.String zobImplements;
    public final java.lang.String zobExtends;

    public JavaZOb(org.gzigzag.Stepper s) {
	    members = (org.gzigzag.Stepper)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC484C93C8000498173235BCA7C9C1FDABFB3FD6CB5FB75794C155E21E7AA2-6"));
	    packageName = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC484C93C8000498173235BCA7C9C1FDABFB3FD6CB5FB75794C155E21E7AA2-7"));
	    path = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC4D544501000466355872D0E82A85FD795CAADD5175D4571B364AB1B81AD7-13"));
	    code = (org.gzigzag.Stepper)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC484C93C8000498173235BCA7C9C1FDABFB3FD6CB5FB75794C155E21E7AA2-8"));
	    zobImplements = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC75C159110004C61A367D8C12CBC1DDFBEE01FE3F34F4E2A96B614F53CDF5-19"));
	    zobExtends = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC75C159110004C61A367D8C12CBC1DDFBEE01FE3F34F4E2A96B614F53CDF5-20"));
    }


}
