/*
 *
 *    You may use and distribute under the terms of either the GNU Lesser
 *    General Public License, either version 2 of the license or,
 *    at your choice, any later version. Alternatively, you may use and
 *    distribute under the terms of the XPL.
 *
 *    See the LICENSE.lgpl and LICENSE.xpl files for the specific terms of
 *    the licenses.
 *
 *    This software is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the README
 *    file for more details.
 *
 */
/*
 *    Generated by GZigZag - DO NOT MODIFY!
 *    If you find something wrong that should be fixed,
 *    PLEASE FIX THE CODE THAT GENERATES THIS CLASS!
 */

package org.gzigzag.impl;

public class ZObMember {
    public final java.lang.String javaName;
    public final java.lang.String defaultValue;
    public final java.lang.String type;

    public ZObMember(org.gzigzag.Stepper s) {
	    javaName = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC4D544501000466355872D0E82A85FD795CAADD5175D4571B364AB1B81AD7-9"));
	    defaultValue = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC4D544501000466355872D0E82A85FD795CAADD5175D4571B364AB1B81AD7-28"));
	    type = (java.lang.String)(org.gzigzag.impl.ZObFactory.getFactory().findMember(s,"0000000008000000EC75E9D5DE000455965B0F3C613E3C331FD32880C6AEAE272603D1F15C2253-25"));
    }


}
