draw: draw.cxx /home/tjl/gummiterm/libgummi/GummiTexture.o
	g++ -o draw -I/home/tjl/gummiterm/libgummi `gdk-pixbuf-config --cflags` draw.cxx `gdk-pixbuf-config --libs` /home/tjl/gummiterm/libgummi/GummiTexture.o -lglut
