# DIAGRAMS=linkorder.png beamorder.png
DIAGRAMS=cursor1.png cursordim.png canvasraster.png rasterspec.png \
	inheritparam.png
DEP=../wmlinc/article.wml

all : zzspec.html zzspec-ns4.html

zzspec.html: zzspec.wml ../keybindings.wml $(DIAGRAMS) $(DEP)

zzspec-ns4.html: zzspec.wml ../keybindings.wml $(DIAGRAMS) $(DEP)

include ../lib.mk



