NOTE: do contact the author (lukka@iki.fi for most of the stuff) if
there is an unfinished part that you really need - I sometimes need
prodding to get things finished. Comments are also appreciated.

NOTE 2: 
THE SUBDIRECTORIES THAT ARE CURRENTLY BEING ACTIVELY WRITTEN ARE
CyberText, DesignProblems and Spec. THE OTHERS ARE A BIT STALE.

I recommend starting with the Gentle_Introduction and then working your
way through the others if the subject matters interests you (for example,
if you are not hacking the internals, CellScroll will not be interesting
to you).

Some of the documents are written in LaTeX using gpic to compile 
diagrams (since it seems more reasonable than e.g. xypic or any
picture language I've seen for LaTeX). See the Makefile for how
the process is supposed to go. The LaTeX files also use rcs.sty,
which is available in the Debian linux package rcs-latex, but also
probably from CTAN. I'm planning to put up autogenerated PostScript 
files of these Real Soon Now.

The files in this directory:

Gentle_Introduction/
	an introduction to what ZigZag is and how it works.

Clang_Design/
	Clang is a language for writing programs using the ZigZag
	structure... no, better to say: Clang is a way of interpreting
	a certain kind of ZigZag structure as a program.
	This document discusses the various issues at stake when 
	designing Clang.

CellScroll/
	CellScrolls are a way to store both the current state
	and all former states of a ZigZag space.

Interfacing/

misc/
	odds and ends

DimBased/
	Some thoughs on reorganization of the model to think about ZZ 
	in the code to be based on dimensions, not so much cells.

PROTOCOL
	ASCII description of the ZZ network protocol. Don't rely on this:
	use the source, Luke.

	The protocol needs some rethinking anyway.

wmlinc/
	Some include files used in the WML (website modeling language)
	files around.
